### ISSUE TITLE
As a user, I can manage tracks in my playlists

### ISSUE THREAD

**Issue by hidingmode** [CS2103-AY1819S1-T13-3/main#23]
Commands to implement (links to User Guide for expected behaviour):
- [x] [`track add p/PLAYLIST t/TRACK`](https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/UserGuide.adoc#adding-a-track-into-a-playlist-code-track-add-code)
- [x] [`track del p/PLAYLIST i/INDEX`](https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/UserGuide.adoc#deleting-a-track-from-a-playlist-code-track-del-code)

**Comment by handshou** [comment]
Working on `track add p/PLAYLIST i/INDEX`

**Comment by handshou** [comment]
Progress completed on `track add p/PLAYLIST t/TRACK` and `track del p/PLAYLIST index`

**Comment by hidingmode** [comment]
Both commands still not working, postponing milestone to v1.4
