### ISSUE TITLE
As a user, I can seek a track

### ISSUE THREAD

**Issue by hidingmode** [CS2103-AY1819S1-T13-3/main#29]
Commands to implement (links to User Guide for expected behaviour):
- [x] [`seek ti/TIME`](https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/UserGuide.adoc#seeking-time-point-code-seek-code)
- [ ] [`step [s/SECONDS]`](https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/UserGuide.adoc#stepping-a-track-code-step-code)
- [ ] [`stepback [s/SECONDS]`](https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/UserGuide.adoc#stepping-back-code-stepback-code)
- [ ] [`replay`](https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/UserGuide.adoc#replay-a-track-code-replay-code)

**Comment by NancyQuris** [comment]
pull request #41  implement part of the function of seek ti/TIME
to-do: finalised those with the new code base and construct test cases

**Comment by NancyQuris** [comment]
pull request #106 gives a full implementation of seek command
