### ISSUE TITLE
Model in Test environment does not have populated FilteredTrackList

### ISSUE THREAD

**Issue by handshou** [CS2103-AY1819S1-T13-3/main#71]
Failing test case in question: `execute_addTrackToPlaylist()`

TestApp's FilteredTrackList seems to be uninitiated.
When TrackAddCommand is not able to retrieve the respective tracks from any tracks list, the expected behaviour breaks.

As such, the Track Add command works on normal run, but fails in testing.

@hidingmode Can clarify if TestApp should initiate playlist lists *and* track lists, or is it already bring initiated?

**Comment by hidingmode** [comment]
I think TestApp doesn't initialize the tracklist

**Comment by hidingmode** [comment]
The getModel() method in TestApp doesnt initialize the tracklist. You can make the ModelHelper and TestApp to set the tracklist.
